module.exports = {
  BEAUTY: "Beauty",
  ELECTRONICS: "Electronics",
  AUTOMOTIVE: "Automotive",
  BOOKS: "Books",
  VIDEO_GAMES: "Video games",
  APPLIANCES: "Appliances",
  HOME_AND_KITCHEN: "Home and kitchen",
  PET_SUPPLIES: "Pet supplies",
  CAMERA_AND_PHOTOGRAPHY: "Camera and photography",
  CELL_PHONES: "Cell phones",
  OUTDOORS: "Outdoors",
  TOYS: "Toys",
  GROCERY: "Grocery",
  MUSICAL_INSTRUMENTS: "Musical instruments",
  OFFICE_PRODUCTS: "Office products",
  ENTERTAINMENT_COLLECTIBLES: "Entertainment collectibles",
  FINE_ART: "Fine art",
  GIFT_CARDS: "Gift cards",
  ONLINE_STORES: "Online stores",
  SPORTS: "Sports",
  BABY: "Baby",
  HEALTH: "Health",
};
